# Generated by Django 3.2.3 on 2021-05-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('way', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyurtma',
            new_name='Order',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Kombo',
        ),
    ]
