# Generated by Django 3.2.3 on 2021-05-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('way', '0002_auto_20210527_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=125),
        ),
    ]
