# Generated by Django 3.2.3 on 2021-06-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('way', '0002_auto_20210624_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_reg',
            name='first_name',
            field=models.CharField(default='', max_length=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot_reg',
            name='last_name',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
