# Generated by Django 3.2.3 on 2021-06-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('way', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='bookmark',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='combo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.JSONField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='foods',
            field=models.ManyToManyField(blank=True, related_name='_way_product_foods_+', to='way.Product'),
        ),
        migrations.AddField(
            model_name='user',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='way.order'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=21, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='price_type',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=125),
        ),
    ]
