# Generated by Django 3.2.3 on 2021-06-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('way', '0005_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cash_payment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='room_number',
        ),
    ]
